### PR TITLE
Migrate to Go mod, remove dep, vendor/

### PR DESCRIPTION
**Pull request by relistan**
This embraces the now-well-supported `go mod` and removes support for `dep` and `vendor/`

### CODE REVIEW

**Comment by mihaitodor** [comment]
Nice one! Looks like you need to update the linter to `curl -sfL "https://install.goreleaser.com/github.com/golangci/golangci-lint.sh" | sh -s -- -b $(go env GOPATH)/bin v1.18.0`

I think you need to tell silly Travis to stop doing `go get ./...` by default using [this](https://github.com/Nitro/haproxy-api/blob/6b2d0fd885c361048172a038acc74e4aa072ebbf/.travis.yml#L13-L15).

Also, if you wish to still use vendoring, [here](https://github.com/Nitro/haproxy-api/blob/6b2d0fd885c361048172a038acc74e4aa072ebbf/.travis.yml#L11) is how to do that. You'll need to do the same on localhost to regenerate the `vendor` folder. Not sure if it's worth the hassle, though, now that they have that module proxy set up.

**Comment by relistan** [comment]
> Nice one! Looks like you need to update the linter to `curl -sfL "https://install.goreleaser.com/github.com/golangci/golangci-lint.sh" | sh -s -- -b $(go env GOPATH)/bin v1.18.0`

Yeah, saw the build failure and committed a bump to 1.21.0 (latest). Thanks

> I think you need to tell silly Travis to stop doing `go get ./...` by default using [this](https://github.com/Nitro/haproxy-api/blob/6b2d0fd885c361048172a038acc74e4aa072ebbf/.travis.yml#L13-L15).

I'll add that.

> 
> Also, if you wish to still use vendoring, [here](https://github.com/Nitro/haproxy-api/blob/6b2d0fd885c361048172a038acc74e4aa072ebbf/.travis.yml#L11) is how to do that. You'll need to do the same on localhost to regenerate the `vendor` folder. Not sure if it's worth the hassle, though, now that they have that module proxy set up.

Thanks, nah, perfectly happy to have all that code out of the repo now that modules seem to just work.

**Comment by mihaitodor** [comment]
> Thanks, nah, perfectly happy to have all that code out of the repo now that modules seem to just work.

Cool! Yeah, I'm also leaning towards forgetting about vendoring :)

Looking more into it, I think `travis_install_go_dependencies` does the right thing if you don't want vendoring. I think the build just failed, because the dependencies will be pulled while `golangci-lint` is running. Probably better to revert that.

**Comment by sbz** [comment]
It's nice to see all these vendor files removed, `go mod` for the win 💯. LGTM 👍

**Pull request merged**
